services:
  db:
    image: postgres:latest
    container_name: nbfp-db
    environment:
      - POSTGRES_USER=nbfpAdmin
      - POSTGRES_PASSWORD=nbfpfeedsmore
      - POSTGRES_DB=nbfpDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: ./server
    container_name: nbfp-api
    ports:
      - "5001:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=nbfpDB;Username=nbfpAdmin;Password=nbfpfeedsmore
volumes:
  pgdata: